server:
  port: 8081
  servlet:
    context-path: /practice6
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: org.hibernate.dialect.MySQLDialect
    url : jdbc:mysql://localhost:3306/practice?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 1qaz@WSX
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    # create, create-drop, update, [none]
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false